"""Add PlannedExpense and ActualExpense models, remove planned_cost from Task

Revision ID: b6708cdf692a
Revises: fbdbf6d07499
Create Date: 2025-02-16 21:07:03.328862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6708cdf692a'
down_revision = 'fbdbf6d07499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actual_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('expense')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('planned_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_cost', sa.FLOAT(), nullable=True))

    op.create_table('expense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.VARCHAR(length=20), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('actual_cost', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planned_expense')
    op.drop_table('actual_expense')
    # ### end Alembic commands ###
